.\" Manpage for distadm.
.\" Contact oks-mgn@mail.ru to correct errors or typos.
.TH DISTADM 1 "25 November 2022" "1.0" "distadm man page"

.SH NAME
distadm \- Distributed Administrator

.SH SYNOPSIS
.B distadm
\fI[<опции>]\fR
\fI[<команда>]\fR

.SH ОПИСАНИЕ
.B distadm
помогает управлять группой компьютеров.
.br
Такие компьютеры называются \fIузлами\fR и сгруппированы в децентрализованную сеть.
Администратор может вводить команды на любом из узлов.
Эти команды будут выполнены на всех узлах в группе.
Например, администратор может ввести имя программы (с возможными аргументами),
запросить состояние узлов, добавить файл для размещения на всех узлах или создать новую учетную запись пользователя.
Узлы могут соединяться по локальной сети.
В текущей версии имеется поддержка только сетей IPv6 и широковещательного режима,
узлы могут общаться только при использовании коммутаторов (свитчей), но не могут, если разделены маршрутизаторами (роутерами).
Информация между узлами так же может передаваться в ручном режиме с помощью файлов,
записываемых на съемные накопители (флешки, оптические диски).
У программы имеется графический интерфейс (GTK-3) и возможность работать в консоли,
где имеется история вводимых команд и автодополнение клавишей Tab.

.SH ОПЦИИ
.TP
\fB\-d\fR, \fB--daemon\fR
Запуск в режиме daemon.
.TP
\fB\-i\fR, \fB--info\fR
Показать информацию о об антивирусе и S.M.A.R.T. узлов.
.TP
\fB\-u\fR, \fB--users\fR
Показать окно для добавления или удаления пользователей. При этом задействуются программы \fIadduser\fR и \fIdeluser\fR.
.TP
\fB\-t\fR, \fB--textmode\fR
Запустить в текстовом режиме.
.TP
\fB\-I\fR, \fB--initialize\fR
Инициализировать новую группу. При этом создастся каталог \fI/var/local/distadm\fR и файлы в нем.
.TP
\fB\-J\fR, \fB--join\fR=\fIФАЙЛ\fR
Присоединить узел к группе, указанной в файле. Смотри команду \fIjoin-group\fR.
.TP
\fB\-c\fR, \fB--config\fR=\fIФАЙЛ\fR
Использовать альтернативный файл конфигурации. По умолчанию используется \fI/usr/local/etc/distadm\fR.
.TP
\fB\-v\fR, \fB--verbose\fR
Показывать дополнительную отладочную информацию.
.TP
\fB--help\fR
Показать краткую справку.
.TP
\fB--version\fR
Показать версию программы.

.SH КОМАНДЫ
.TP
\fBaddfile\fR \fR\fIФАЙЛ\fR \fR\fI[ПОДКАТАЛОГ]\fR
Добавить файл. Файл будет распространен между узлами (компьютерами) и помещен в специальный каталог программы,
по умолчанию \fI/var/local/distadm/files\fR.
Если \fIПОДКАТАЛОГ\fR указан, файл будет помещен в этот подкаталог каталога программы.
.TP
\fBadduser\fR \fR\fIЛОГИН\fR
Создать в системе новую учетную запись. При этом будет задействована программа \fIadduser\fR.
.TP
\fBcancel-invite\fR
Отменить у узла статус \fIinviter\fR.
Текущий статус узла можно узнать командой \fIstatus\fR.
Когда узел создает файл с оффлайн приглашением, его статус меняется с \fIwork\fR на \fIinviter\fR.
Когда оффлайн приглашение завершается командой \fIfinalize-invite\fR, статус меняется обратно на \fIwork\fR.
Если файл оффлайн приглашения утерян, статус \fIwork\fR может быть восстановлен командой \fIcancel-invite\fR.
.TP
\fBdeldir\fR \fR\fIПОДКАТАЛОГ\fR
Удалить подкаталог из рабочего каталога программы со всем содержимым на всех узлах.
По умолчанию рабочим каталогом является \fI/var/local/distadm/files\fR.
.TP
\fBdelexec\fR \fR\fI[ПРОГРАММА]\fR
Удалить результат выполнения программы (текст, выведенный программой в консоль). Смотри \fIexec\fR.
Если \fIПРОГРАММА\fR указана, удаляются только результаты этой программы.
.TP
\fBdelfile\fR \fR\fIФАЙЛ\fR
Удалить файл со всех узлов.
.TP
\fBdellog\fR
Удалить внутренний журнал программы distadm (смотри \fIshowlog\fR).
.TP
\fBdelnode\fR \fR\fIУЗЕЛ\fR \fR\fI[force]\fR
Удалить узел из группы.
\fIУЗЕЛ\fR - это UUID или текстовое имя компьютера (hostname).
Список известных узлов можно посмотреть командой \fIlistnodes\fR.
Когда указанный узел получает команду на удаление, его статус меняется на \fIdeleting\fR.
После этого требуется записать пакет с этого узла (смотри \fIwrite-packet\fR).
В нем будет содержаться сообщение о том, что узел удален.
Когда другие узлы получат такое сообщение, они удалят узел из своих записей.
Команда \fIlistnodes\fR больше не будет показывать удаленный узел.
После этого на удаленном узле можно остановить программу и стереть все файлы программы.
Если доступ к удаляемому узлу невозможен (например, по причине поломки компьютера), нужно указать флаг \fR\fIforce\fR.
Однако это может привести к некоторым проблемам:
последние команды от удаленного узла будут выполнены только на части узлов группы, но не на всех.
.TP
\fBdeluser\fR \fR\fIЛОГИН\fR
Удалить учетную запись на узлах.
Эта команда позволяет удалять только учетные записи, созданные командой \fIadduser\fR.
Для удаления других учетных записей можно, например, указать команду \fIexec\fR \fIdeluser\fR \fI<логин>\fR.
.TP
\fBantivirus\fR
Показать информацию об антивирусе.

.TP
\fBexec\fR \fR\fIПРОГРАММА\fR \fR\fI[ПАРАМЕТРЫ]\fR
Выполнить программу на каждом узле в группе.
Для этого используется интерпретатор 'sh', поэтому допускается ипользование специальных символов типа '<', '>', '|', '&&' и т.д.
Рабочим каталогом по умолчанию является \fI/var/local/distadm/files\fR.
Другим способом выполнения команд может быть написание временного файла-скрипта,
его размещение на узлах с помощью команды \fIaddfile\fR,
запуск с помощью \fIexec\fR и удаление командой \fIdelfile\fR, например:
.sp
# echo '#/bin/bash' > my.sh
.br
# echo 'echo test > /tmp/test && sleep 1' >> my.sh
.br
# distadm addfile my.sh
.br
# distadm exec chmod 0700 my.sh
.br
# distadm exec ./my.sh
.br
# distadm delfile my.sh
.br
# rm my.sh

.TP
\fBexit\fR
Выйти из интерактивного режима работы программы. Так же работает комбинация клавиш Ctrl+D.
.TP
\fBfinalize-invite\fR \fR\fIФАЙЛ\fR
Когда другие узлы присоединятся к группе с помощью файла оффлайн приглашения (смотри команду \fIjoin-group\fR),
этот файл будет содержать информацию о присоединившихся узлах и он должен быть возвращен приглашающему узлу.
Этот узел с помощью команды \fIfinalize-invite\fR откроет файл приглашения, прочитает информацию о новых узлах
и создаст для них сообщение-приветствие.
Это сообщение должно быть помещено в новый файл-пакет командой \fIwrite-packet\fR.
Когда новый узел прочитает файл с сообщением-приветствием и своим идентификатором, он поменяет свой статус на 'work'.
.TP
\fBhelp\fR
Показать список доступных команд.
.TP
\fBjoin-group\fR \fR\fIФАЙЛ\fR
Присоединить узел (этот компьютер) к существующей группе с помощью файла приглашения.
Такой файл может быть создан командой \fIwrite-online-invite\fR или \fIwrite-offline-invite\fR.
Если файл является онлайн-приглашением, статус узла будет 'uninitialized'
и узел будет ждать подключения к другим узлам группы по сети.
После удачного подключения его статус поменяется на 'work'.
Если файл является оффлайн-приглашением, статус узла будет 'partially-initialized',
узел запишет в файл дополнительную информацию и будет ждать файла-пакета от группы с приветствием
(смотри команды \fIfinalize-invite\fR и \fIread-packet\fR).
После прочтения файла-пакета статус поменяется на 'work'.
.TP
\fBlistfiles\fR
Показать список файлов, загруженных в программу командой \fIaddfile\fR.
.TP
\fBlistnodes\fR
Показать список узлов в группе.
.TP
\fBlistonline\fR
Показать список узлов и информацию о том, когда они последний раз работали.
Команда предназначена для поиска неработающих узлов.
.TP
\fBlistusers\fR
Показать список пользователей, созданных командой \fIadduser\fR.
.TP
\fBlocal-id\fR
Показать идентификатор текущего узла и группы.
.TP
\fBnodesinfo\fR
Показать информацию об узлах и матрицу команд. Используется для поиска поврежденных узлов.
.TP
\fBqueue\fR
Показать список узлов и длину очереди команд для них.
Большие значения очереди означают, что имеется большое количество сообщений для передачи этому узлу.
Сообщения могут быть переданы по сети или с помощью файлов-пакетов (смотри команду \fIwrite-packet\fR).
Не забывайте передавать информацию и в обратном направлении от этого узла.
.TP
\fBread-packet\fR \fR\fIФАЙЛ\fR
Прочитать файл-пакет.
Такие файлы содержат новые команды для исполнения, новые сообщения, статусы узлов и другую информацию.
.TP
\fBshow-exec\fR \fR\fI[ПРОГРАММА]\fR
Показать результаты работы программ (вывод в консоль), выполненных с помощью команды \fIexec\fR.
Если \fIПРОГРАММА\fR указана, отобразится только результат работы этой программы.
.TP
\fBshowlog\fR
Показать внутренний журнал программы distadm log.
В текущей версии он содержит только информацию об удаленных узлах (смотри команду \fIdelnode\fR).
.TP
\fBstatus\fR
Показать статус узла:
.RS
.sp
\fBuninitialized\fR
узел присоединился к группе с помощью онлайн-приглашения и ожидает подключения к другим узлам по сети.
.sp
\fBpartially-initialized\fR
узел присоединился к группе с помощью оффлайн-приглашения и ожидает файла-пакета.
.sp
\fBwork\fR
узел работает в штатном режиме. Основной режим работы.
.sp
\fBinviter\fR
узел является оффлайн-приглашающим и потребляет дополнительные ресурсы
(смотри команды \fIwrite-offline-invite\fR, \fIfinalize-invite\fR).
.sp
\fBdeleting\fR
узел удален (смотри команду \fIdelnode\fR). Он не может создавать и получать новые команды.
.sp
\fBdeleted\fR то же, что \fIdeleting\fR, но программа сразу завершается.
.RE
.TP
\fBstored-commands\fR
Показать команды, хранящиеся на узле.
Они передаются другим узлам по сети или с помощью файлов-пакетов, создаваемых командой \fIwrite-packet\fR.
Команды удаляются из узла когда они выполнены на нем и этот узел знает, что все другие узлы тоже знают эти команды.
.TP
\fBwrite-offline-invite\fR \fR\fIFILE\fR
Записать файл оффлайн-приглашения, который содержит всю необходимую информацию для инициализации нового узла.
Этот файл может иметь большой размер, потому что он содержит все файлы, добавленные командой \fIaddfile\fR.
.TP
\fBwrite-online-invite\fR \fR\fIFILE\fR
Записать файл онлайн-инициализации, содержащий идентификатор группы.
Этого достаточно для того, чтобы подключиться к другим узлам группы по сети и получить всю необходимую информацию для инициализации.
.TP
\fBwrite-packet\fR \fR\fIFILE\fR
Записать файл-пакет с новыми командами, сообщениями, статусами узлов и другой информацией.
Этот файл может быть большим потому что он содержит новые файлы, добавленные командой \fIaddfile\fR.
Каждый раз, когда такой файл создается он содержит всю информацию, необходимую для передачи другим узлам.
Поэтому, если такой файл будет случайно утерян, его можно создать заново.
Рекомендуется записывать сразу на съемный диск (флешку), потому что программа проверяет доступное для записи место
и корректно прекращает запись файла, если свободного места больше не осталось.

.SH ПРИМЕРЫ
Запуск в режиме daemon:
.sp
.RS 4
distadm -d
.RE
.sp

Интерактивный запуск:
.RS 4
.sp
distadm
.RE

Создание новой группы:
.RS 4
.sp
distadm -I
.RE

Запись оффлайн-приглашения в файл my-init.bin:
.RS 4
.sp
distadm write-offline-invite my-init.bin
.RE

Присоединение узла к группе с помощью файла-приглашения my-init.bin:
.RS 4
.sp
distadm -J my-init.bin
.RE

Завершение оффлайн-приглашений на приглашающем узле с помощью файла оффлайн-приглашения my-init.bin:
.RS 4
.sp
distadm finalize-invite my-init.bin
.RE

Запись файла-пакета my.pkt для распространения между узлами группы (с использованием флешек, оптических дисков и т.п.):
.RS 4
.sp
distadm write-packet my.pkt
.RE

Чтение файла-пакета my.pkt:
.RS 4
.sp
distadm read-packet my.pkt
.RE

Установить gzip:
.RS 4
.sp
distadm exec apt install gzip
.RE

Установить deb-пакет из файла my.deb:
.RS 4
.sp
distadm addfile my.deb
.br
distadm exec dpkg -i my.deb
.RE

Показать заполненность дисков на узлах:
.sp
.RS 4
distadm exec df
.br
distadm showexec
.RE

.SH ОШИБКИ
Известные ошибки устранены. Новые пока не выявлены.
.SH АВТОР
Ощепков Константин (oks-mgn@mail.ru)
